# Generated by Django 4.1 on 2022-08-08 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('adress', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=9)),
                ('typeclient', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codevente', models.CharField(max_length=10)),
                ('dtevente', models.DateField(auto_now_add=True)),
                ('prix', models.FloatField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeprod', models.CharField(max_length=100)),
                ('qte', models.IntegerField(default=0)),
                ('dteprod', models.DateField(blank=True, null=True)),
                ('qtedechet', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='stockapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qteapp', models.IntegerField(null=True)),
                ('qteappseuil', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='stockvente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtevente', models.IntegerField(default=0)),
                ('qtedechet', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profil', models.CharField(max_length=100)),
                ('pseudo', models.CharField(max_length=50)),
                ('mdepass', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte', models.IntegerField(default=0)),
                ('prix', models.FloatField(default=0)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prod.client')),
                ('facture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prod.facture')),
            ],
        ),
        migrations.AddField(
            model_name='facture',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prod.utilisateur'),
        ),
        migrations.CreateModel(
            name='etape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('qteproduite', models.IntegerField()),
                ('qtedechet', models.IntegerField()),
                ('coutdeletape', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('description', models.TextField()),
                ('prod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prod.production')),
            ],
        ),
        migrations.CreateModel(
            name='approvisionnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dte', models.DateField(blank=True, null=True)),
                ('coutachat', models.FloatField(blank=True)),
                ('coutsupp', models.FloatField(blank=True)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prod.fournisseur')),
            ],
        ),
    ]
